name: Python Tests

on:
    push:

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   name: Install Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.8'

            -   name: Restore pip Download Cache
                uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: pip-${{ hashFiles('requirements/**.txt') }}

            -   name: Upgrade pip to Latest and Install pip Dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run Django Tests
                run: python manage.py test